# Generated by Django 5.1.6 on 2025-05-27 16:52

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BytequestBaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated Date')),
                ('user_type', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Dev', 'Developer'), ('Other', 'Other')], db_index=True, default='User', max_length=10, verbose_name='User Type')),
                ('full_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1, null=True, verbose_name='Gender')),
                ('age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Age')),
                ('dob', models.DateField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Super User')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('is_rejected', models.BooleanField(db_index=True, default=False, verbose_name='Rejected')),
                ('is_aproved', models.BooleanField(db_index=True, default=False, verbose_name='Aproved')),
                ('is_blocked', models.BooleanField(db_index=True, default=False, verbose_name='Blocked')),
                ('email_verify', models.BooleanField(default=False, verbose_name='Email Verify')),
                ('login_status', models.BooleanField(default=False, verbose_name='Login Status')),
                ('otp_verify', models.BooleanField(default=False, verbose_name='opt Verified')),
                ('otp', models.CharField(blank=True, max_length=4, null=True, verbose_name='OTP')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('twitter_user_id', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_type', models.CharField(max_length=100)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
